// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_1dRIC_i94nze0hDLLAX-VK_TLi9wVwM',
    appId: '1:821360468155:web:27a48fd407c4c9d8f6c99e',
    messagingSenderId: '821360468155',
    projectId: 'materialist-4f472',
    authDomain: 'materialist-4f472.firebaseapp.com',
    storageBucket: 'materialist-4f472.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2cqzwonexlhZTcNgC8jbnJQt9JsdY3Cg',
    appId: '1:821360468155:android:20ddcfa1f920ff20f6c99e',
    messagingSenderId: '821360468155',
    projectId: 'materialist-4f472',
    storageBucket: 'materialist-4f472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6S11QTDj_nWtd9Ps_syQQ-eOTN-q_82Y',
    appId: '1:821360468155:ios:c1c03a97308ced14f6c99e',
    messagingSenderId: '821360468155',
    projectId: 'materialist-4f472',
    storageBucket: 'materialist-4f472.appspot.com',
    iosClientId: '821360468155-m6ok5kjpgg4or3o6q999n53891lgshsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.materialist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6S11QTDj_nWtd9Ps_syQQ-eOTN-q_82Y',
    appId: '1:821360468155:ios:c1c03a97308ced14f6c99e',
    messagingSenderId: '821360468155',
    projectId: 'materialist-4f472',
    storageBucket: 'materialist-4f472.appspot.com',
    iosClientId: '821360468155-m6ok5kjpgg4or3o6q999n53891lgshsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.materialist',
  );
}
