// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTN7yHZWIXNBNI5PCJU02q0_A5qtecBjs',
    appId: '1:36668038205:web:4f656e9efec13f52895e54',
    messagingSenderId: '36668038205',
    projectId: 'materiallist-fec4c',
    authDomain: 'materiallist-fec4c.firebaseapp.com',
    storageBucket: 'materiallist-fec4c.appspot.com',
    measurementId: 'G-QGKRLCFLHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpmxJncPKySUsqZ_42RxK7fBdhLEwBcA',
    appId: '1:36668038205:android:3a72162ffa282135895e54',
    messagingSenderId: '36668038205',
    projectId: 'materiallist-fec4c',
    storageBucket: 'materiallist-fec4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOyGA82hfd4E5ZVVr3FVRshzZ1Ug6CgVc',
    appId: '1:36668038205:ios:70234e12a9f3f945895e54',
    messagingSenderId: '36668038205',
    projectId: 'materiallist-fec4c',
    storageBucket: 'materiallist-fec4c.appspot.com',
    iosClientId: '36668038205-gghbljdq5gjjujhi11vv64u0lud7ed8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.materialist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOyGA82hfd4E5ZVVr3FVRshzZ1Ug6CgVc',
    appId: '1:36668038205:ios:70234e12a9f3f945895e54',
    messagingSenderId: '36668038205',
    projectId: 'materiallist-fec4c',
    storageBucket: 'materiallist-fec4c.appspot.com',
    iosClientId: '36668038205-gghbljdq5gjjujhi11vv64u0lud7ed8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.materialist',
  );
}
